version: '3'

volumes:
  db-data:
  bootstrap_cache:
  storage:
  node_modules:
  vendor:

services:
  php-cli: # Web server for remote debug on PhpStorm.
    build: ./docker
    volumes:
      - ./src/test:/var/www/html/
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - bootstrap_cache:/var/www/html/bootstrap/cache
      # - storage_framework:/var/www/html/storage/
      - node_modules:/var/www/html/node_modules
      - vendor:/var/www/html/vendor
    working_dir: /var/www/html
    container_name: php-cli
    depends_on:
      - postgres
    restart: always

  web:
    build: ./docker
    ports:
      - 8081:80
      # - 443:443
    volumes:
      - ./src/test:/var/www/html/
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - bootstrap_cache:/var/www/html/bootstrap/cache
      # - storage:/var/www/html/storage/
      - node_modules:/var/www/html/node_modules
      - vendor:/var/www/html/vendor
    working_dir: /var/www/html
    container_name: web
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:10.8
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment: # Set the postgres user name, password and database name.
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    hostname: postgres
    container_name: postgres
    restart: always

  pgadmin4:
    image: dpage/pgadmin4:4.2
    ports:
        - 8000:80
    volumes:
        - ./docker/pgadmin4:/var/lib/pgadmin
    environment: # Set the login information of pgAdmin 4.
        PGADMIN_DEFAULT_EMAIL: root
        PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    container_name: pgadmin4
    depends_on:
      - postgres
    restart: always
